baseurl: http://new.eightypercent.net/
languageCode: en-us
title: 80%
description: The personal blog of Joe Beda
uglyurls: true
pluralizelisttitles: false
paginate: 10

taxonomies:
  archive: archive

params:
  description: "The personal blog of Joe Beda"